# 8.6.3 ghci hangs all the time on windows, wait for 8.6.4
# resolver: lts-13.9
# stay with 8.2.2 for now
resolver: lts-11.22

packages:
- thunderbuns

extra-deps:
- git: https://github.com/grmble/hs-bunyan.git
  commit: 4f3bb35ed53f39d94d13614d0b6c090e5ff6cb76 
  subdirs:
  - bunyan
  - bunyan-freer
  - bunyan-pid
  - bunyan-rio
  - picolens
- git: https://github.com/grmble/hs-d64.git
  commit: e9105efcd929418dfd415c2a5ddd367616e3fe75
  subdirs:
  - d64
  - d64-uuid
