# need nightly for dhall 1.11 (2018-03-10), but it's not in f*cking 2018-03-12
# need more recent nightly for servant 1.13 - streaming support (2018-03-12)
resolver: nightly-2018-03-12

packages:
- .

extra-deps: 
- dhall-1.11.0
- ansi-terminal-0.7.1.1
- git: https://github.com/grmble/tprocess.git
  commit: 06e76c2ab709d2f2326498b1d3cca6f830dc0a1c
- git: https://github.com/grmble/tcql4.git
  commit: 32fc43f0ceae87ec2e295916b72c428ce4a8476e
- git: https://github.com/grmble/hexdump-xxd.git
  commit: 68a7f84e3466009934406534422441ee78527b47
