# need nightly for dhall 1.11 (2018-03-10), but it's not in f*cking 2018-03-12
# need more recent nightly for servant 1.13 - streaming support (2018-03-12)
# lts-11.5 should workd (2018-04-21)
resolver: lts-11.7

packages:
- hexdump-xxd
- picolens
- tfreetime
- tlogger
- tprocess
- thunderbuns

extra-deps: 
# - dhall-1.11.0
# - ansi-terminal-0.7.1.1
- git: https://github.com/grmble/tcql4.git
  commit: 32fc43f0ceae87ec2e295916b72c428ce4a8476e
